//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerEx.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorerEx.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ， 的本地化字符串。
        /// </summary>
        internal static string __ {
            get {
                return ResourceManager.GetString(", ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用说明：
        ///ExplorerEx [-h|--help] [-r|--runInBackground] [-o|--openInNewWindow] [-d|--requireDebugger] Path1, Path2, ... 的本地化字符串。
        /// </summary>
        internal static string _App_help {
            get {
                return ResourceManager.GetString("#App_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不能包含下列字符：
        /// \ / : * ? &quot; &lt; &gt; | 的本地化字符串。
        /// </summary>
        internal static string _InvalidFileName {
            get {
                return ResourceManager.GetString("#InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件是二进制文件或者使用了不支持的编码方式。 的本地化字符串。
        /// </summary>
        internal static string _Unsupported_encoding {
            get {
                return ResourceManager.GetString("#Unsupported_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝访问 的本地化字符串。
        /// </summary>
        internal static string Access_denied {
            get {
                return ResourceManager.GetString("Access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加到收藏夹 的本地化字符串。
        /// </summary>
        internal static string Add_to_bookmarks {
            get {
                return ResourceManager.GetString("Add_to_bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果改变文件拓展名，则可能导致文件不可用。
        ///
        ///确定要更改吗？ 的本地化字符串。
        /// </summary>
        internal static string Are_you_sure_to_change_extension {
            get {
                return ResourceManager.GetString("Are_you_sure_to_change_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要永久删除选择的文件吗？ 的本地化字符串。
        /// </summary>
        internal static string Are_you_sure_to_delete_these_files_Permanently_ {
            get {
                return ResourceManager.GetString("Are_you_sure_to_delete_these_files_Permanently?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要将选择的文件移动到回收站吗？ 的本地化字符串。
        /// </summary>
        internal static string Are_you_sure_to_recycle_these_files_ {
            get {
                return ResourceManager.GetString("Are_you_sure_to_recycle_these_files?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序（小的在上） 的本地化字符串。
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用： 的本地化字符串。
        /// </summary>
        internal static string Available__ {
            get {
                return ResourceManager.GetString("Available: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用空间 的本地化字符串。
        /// </summary>
        internal static string Available_space {
            get {
                return ResourceManager.GetString("Available_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回到首页 的本地化字符串。
        /// </summary>
        internal static string Back_to_home {
            get {
                return ResourceManager.GetString("Back_to_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大图标 的本地化字符串。
        /// </summary>
        internal static string Big_icon {
            get {
                return ResourceManager.GetString("Big_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏夹 的本地化字符串。
        /// </summary>
        internal static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法访问文件夹 的本地化字符串。
        /// </summary>
        internal static string Cannot_access_directory {
            get {
                return ResourceManager.GetString("Cannot_access_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法创建 的本地化字符串。
        /// </summary>
        internal static string Cannot_create {
            get {
                return ResourceManager.GetString("Cannot_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开 的本地化字符串。
        /// </summary>
        internal static string Cannot_open {
            get {
                return ResourceManager.GetString("Cannot_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开此路径 的本地化字符串。
        /// </summary>
        internal static string Cannot_open_path {
            get {
                return ResourceManager.GetString("Cannot open path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光盘驱动器 的本地化字符串。
        /// </summary>
        internal static string CD_drive {
            get {
                return ResourceManager.GetString("CD_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查您的输入后再试。 的本地化字符串。
        /// </summary>
        internal static string Check_your_input_and_try_again {
            get {
                return ResourceManager.GetString("Check_your_input_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到 的本地化字符串。
        /// </summary>
        internal static string Copy_to {
            get {
                return ResourceManager.GetString("Copy_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认收藏夹 的本地化字符串。
        /// </summary>
        internal static string Default_bookmark {
            get {
                return ResourceManager.GetString("Default_bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序（大的在上） 的本地化字符串。
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面 的本地化字符串。
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细信息 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不要再显示该信息 的本地化字符串。
        /// </summary>
        internal static string Dont_show_this_message_again {
            get {
                return ResourceManager.GetString("Dont_show_this_message_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备未就绪。 的本地化字符串。
        /// </summary>
        internal static string DriveIsNotReady {
            get {
                return ResourceManager.GetString("DriveIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑收藏项 的本地化字符串。
        /// </summary>
        internal static string EditBookmark {
            get {
                return ResourceManager.GetString("EditBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空文件夹 的本地化字符串。
        /// </summary>
        internal static string Empty_folder {
            get {
                return ResourceManager.GetString("Empty_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything未运行或未安装，暂时无法使用搜索。 的本地化字符串。
        /// </summary>
        internal static string Everything_is_not_available {
            get {
                return ResourceManager.GetString("Everything_is_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出应用程序 的本地化字符串。
        /// </summary>
        internal static string Exit_application {
            get {
                return ResourceManager.GetString("Exit_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件失败 的本地化字符串。
        /// </summary>
        internal static string FailedToOpenFile {
            get {
                return ResourceManager.GetString("FailedToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        internal static string File_size {
            get {
                return ResourceManager.GetString("File_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件系统 的本地化字符串。
        /// </summary>
        internal static string File_system {
            get {
                return ResourceManager.GetString("File_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充占比 的本地化字符串。
        /// </summary>
        internal static string Fill_ratio {
            get {
                return ResourceManager.GetString("Fill_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组依据 的本地化字符串。
        /// </summary>
        internal static string Group_by {
            get {
                return ResourceManager.GetString("Group_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建链接 的本地化字符串。
        /// </summary>
        internal static string Link_to {
            get {
                return ResourceManager.GetString("Link_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中…… 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载图片： 的本地化字符串。
        /// </summary>
        internal static string Loading_image_from {
            get {
                return ResourceManager.GetString("Loading_image_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地磁盘 的本地化字符串。
        /// </summary>
        internal static string Local_disk {
            get {
                return ResourceManager.GetString("Local_disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改日期 的本地化字符串。
        /// </summary>
        internal static string Modification_date {
            get {
                return ResourceManager.GetString("Modification_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到 的本地化字符串。
        /// </summary>
        internal static string Move_to {
            get {
                return ResourceManager.GetString("Move_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        internal static string New_folder {
            get {
                return ResourceManager.GetString("New_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在新标签页中打开 的本地化字符串。
        /// </summary>
        internal static string OpenInNewTab {
            get {
                return ResourceManager.GetString("OpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在新窗口中打开 的本地化字符串。
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他类型磁盘 的本地化字符串。
        /// </summary>
        internal static string Other_type_disk {
            get {
                return ResourceManager.GetString("Other_type_disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速访问 的本地化字符串。
        /// </summary>
        internal static string Quick_access {
            get {
                return ResourceManager.GetString("Quick_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回收站 的本地化字符串。
        /// </summary>
        internal static string Recycle_bin {
            get {
                return ResourceManager.GetString("Recycle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 松手添加到收藏夹 的本地化字符串。
        /// </summary>
        internal static string Release_to_add_to_bookmark {
            get {
                return ResourceManager.GetString("Release_to_add_to_bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 松手移动到回收站 的本地化字符串。
        /// </summary>
        internal static string Release_to_move_to_recycle_bin {
            get {
                return ResourceManager.GetString("Release_to_move_to_recycle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我的选择，下次不再询问 的本地化字符串。
        /// </summary>
        internal static string Remember_my_choice_and_dont_ask_again {
            get {
                return ResourceManager.GetString("Remember_my_choice_and_dont_ask_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可移动磁盘 的本地化字符串。
        /// </summary>
        internal static string Removable_disk {
            get {
                return ResourceManager.GetString("Removable_disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从收藏夹移除 的本地化字符串。
        /// </summary>
        internal static string RemoveFromBookmarks {
            get {
                return ResourceManager.GetString("RemoveFromBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  个项目 的本地化字符串。
        /// </summary>
        internal static string Run_ItemsCount {
            get {
                return ResourceManager.GetString("Run_ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择了  的本地化字符串。
        /// </summary>
        internal static string Run_SelectedItemsCount {
            get {
                return ResourceManager.GetString("Run_SelectedItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以管理员身份运行 的本地化字符串。
        /// </summary>
        internal static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 的本地化字符串。
        /// </summary>
        internal static string Save_as {
            get {
                return ResourceManager.GetString("Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为文件 的本地化字符串。
        /// </summary>
        internal static string Save_as_file {
            get {
                return ResourceManager.GetString("Save_as_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件名 的本地化字符串。
        /// </summary>
        internal static string Save_file_name {
            get {
                return ResourceManager.GetString("Save_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分享 的本地化字符串。
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷方式 的本地化字符串。
        /// </summary>
        internal static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示窗口 的本地化字符串。
        /// </summary>
        internal static string Show_window {
            get {
                return ResourceManager.GetString("Show_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小图标 的本地化字符串。
        /// </summary>
        internal static string Small_icon {
            get {
                return ResourceManager.GetString("Small_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下文件删除失败： 的本地化字符串。
        /// </summary>
        internal static string The_following_files_failed_to_delete {
            get {
                return ResourceManager.GetString("The_following_files_failed_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此电脑 的本地化字符串。
        /// </summary>
        internal static string This_computer {
            get {
                return ResourceManager.GetString("This_computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平铺 的本地化字符串。
        /// </summary>
        internal static string Tile {
            get {
                return ResourceManager.GetString("Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共有： 的本地化字符串。
        /// </summary>
        internal static string Total__ {
            get {
                return ResourceManager.GetString("Total: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总容量 的本地化字符串。
        /// </summary>
        internal static string Total_space {
            get {
                return ResourceManager.GetString("Total_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的参数： 的本地化字符串。
        /// </summary>
        internal static string Unknown_argument {
            get {
                return ResourceManager.GetString("Unknown_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string Unknown_error {
            get {
                return ResourceManager.GetString("Unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知类型 的本地化字符串。
        /// </summary>
        internal static string Unknown_type {
            get {
                return ResourceManager.GetString("Unknown_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您关闭了最后一个标签页，请问您希望？ 的本地化字符串。
        /// </summary>
        internal static string You_closed_the_last_tab_what_do_you_want_ {
            get {
                return ResourceManager.GetString("You_closed_the_last_tab_what_do_you_want?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你打开了多个标签页，确定要关闭吗？ 的本地化字符串。
        /// </summary>
        internal static string You_have_opened_more_than_one_tab {
            get {
                return ResourceManager.GetString("You_have_opened_more_than_one_tab", resourceCulture);
            }
        }
    }
}
